"""add conversation ownership

Revision ID: 99abb27341e1
Revises: 5e21d3d54777
Create Date: 2026-08-14 00:54:16.821537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99abb27341e1'
down_revision: Union[str, Sequence[str], None] = '5e21d3d54777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversations',
        sa.Column('user_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        'conversations',
        'users',
        ['user_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        'conversations',
        type_='foreignkey'
    )
    op.drop_column(
        'conversations',
        'user_id'
    )
    # ### end Alembic commands ###
